### ISSUE TITLE
Supply work records via NTA

### ISSUE THREAD

**Issue by HenryQW** [RSS3-Network/Global-Indexer#153]
Implement the actual handler to return the data.

https://github.com/RSS3-Network/Explorer/issues/18
https://github.com/RSS3-Network/Global-Indexer/issues/142

**Comment by HenryQW** [comment]
Supplied via `/nta/epochs/:node`

**Comment by Songkeys** [comment]
@polebug Is this API changed? didn't see this in the [openapi](https://petstore.swagger.io/?url=https://gi.rss3.dev/docs/openapi.json#/Epoch).

<img width="752" alt="SCR-20240904-laxc" src="https://github.com/user-attachments/assets/67bfb0cf-55f8-4fdb-871d-1eb47fc4c59f">
